spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - account_email
              - name
              - birthday
              - birthyear
              - age_range
              - gender
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: ${NAVER_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - email
              - name
              - birthday
              - birthyear
              - age
              - gender
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - email
              - profile
              - https://www.googleapis.com/auth/user.birthday.read
              - https://www.googleapis.com/auth/profile.agerange.read
              - https://www.googleapis.com/auth/user.gender.read
          apple:
            client-id: ${APPLE_CLIENT_ID}
            client-authentication-method: client_secret_post
            redirect-uri: ${APPLE_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-name: Apple
            scope:
              - name
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize?response_mode=form_post
            token-uri: https://appleid.apple.com/auth/token
            public-key-uri: https://appleid.apple.com/auth/keys
            user-name-attribute: sub

apple:
  url: ${APPLE_URL}
  key-path: ${APPLE_KEY_PATH}
  client-id: ${APPLE_CLIENT_ID}
  team-id: ${APPLE_TEAM_ID}
  key-id: ${APPLE_KEY_ID}