spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(9Z6DKoVAi506YeSk/5sn+HjZ4zTtvbSciOFtWlKXSk1mmkvRZolPniTRNbGgDLz9)
            client-secret: ENC(BBNo5ldktHfZhnmLejtKHCGjGWLHFu9iD7doNKrWz/2MNYjuNxFQe+9AB+FqA2XL)
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - account_email
              - name
              - birthday
              - birthyear
              - age_range
              - gender
          naver:
            client-id: ENC(FGYIfJlxdtT4NyOxnV80uuttXOM8NI1FUcsBqSyUmtk=)
            client-secret: ENC(9y68M+H96/5a0h6oX1zgAKCC27yBO5ll)
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - email
              - name
              - birthday
              - birthyear
              - age
              - gender
          google:
            client-id: ENC(xFTwpvTGxef+wwSfLB8qByEeI2TYMcU3iL29iKCBWBOB8f4ZIx8+c52XhlOeykD0d9MxI3ImOu5Rm39LUEORl/7eMfO6W/xXxuhHKwl2eJjQlUmcy0LNSg==)
            client-secret: ENC(FsYy9X+Zw3EEL69+6b2q1tm+DBsZA2fbKWh2MCKM8PWPqD7Ri1rC7hyxGeZCuH+D)
            scope:
              - email
              - profile
              - https://www.googleapis.com/auth/user.birthday.read
              - https://www.googleapis.com/auth/profile.agerange.read
              - https://www.googleapis.com/auth/user.gender.read
          apple:
            client-id: ENC(VS8LFA0hL4ni+mPBHg78TtsQF4B6wB62JEbo7NMT3k8=)
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/apple
            authorization-grant-type: authorization_code
            client-name: Apple
            scope:
              - name
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response
          apple:
            authorizationUri: https://appleid.apple.com/auth/authorize?response_mode=form_post
            tokenUri: https://appleid.apple.com/auth/token
            user-name-attribute: sub

apple:
  url: ${APPLE_URL}
  key-path: ${APPLE_KEY_PATH}
  client-id: ${APPLE_CLIENT_ID}
  team-id: ${APPLE_TEAM_ID}
  key-id: ${APPLE_KEY_ID}