spring:
  profiles:
    default: local
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_ID}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import:
      - application-oauth2.yml

jwt:
  expiry:
    access-token: 3600000 #60 * 60 * 1000 (1 hour)
    refresh-token: 604800000 #7 * 24 * 60 * 60 * 1000 (7 days)
  secret-key: ${JWT_SECRET_KEY}

jasypt:
  encryptor:
    bean: jasyptEncryptor
    key: ${JASYPT_ENCRYPTOR_KEY}

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        highlight_sql: true
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
  data:
    web:
      pageable:
        one-indexed-parameters: true

logging:
  level:
    root: info
    org.hibernate.sql: info
    org.hibernate.type.descriptor.sql: trace
    com.project.foradhd: debug

---
spring:
  config:
    activate:
      on-profile: dev
    import: aws-parameterstore:/db-config/dev/
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        highlight_sql: true
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
  data:
    web:
      pageable:
        one-indexed-parameters: true

logging:
  level:
    root: info
    org.hibernate.sql: info
    org.hibernate.type.descriptor.sql: trace
    com.project.foradhd: debug

---
spring:
  config:
    activate:
      on-profile: prod
    import: aws-parameterstore:/db-config/prd/
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        highlight_sql: true
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
  data:
    web:
      pageable:
        one-indexed-parameters: true

logging:
  level:
    root: info
    org.hibernate.sql: info
    org.hibernate.type.descriptor.sql: info
    com.project.foradhd: info
