spring:
  profiles:
    default: local
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_ID}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import:
      - application-oauth2.yml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  servlet:
    multipart:
      max-file-size: 5MB #하나의 파일 용량 제한
      max-request-size: 10MB #하나의 요청 내 전체 파일 용량 제한
      resolve-lazily: true #실제 파일에 접근하는 시점에 파일 용량 체크 (스프링 MVC에서 예외 throw)

jwt:
  expiry:
    access-token: 3600000 #60 * 60 * 1000 (1 hour)
    refresh-token: 604800000 #7 * 24 * 60 * 60 * 1000 (7 days)
  secret-key: ${JWT_SECRET_KEY}

jasypt:
  encryptor:
    bean: jasyptEncryptor
    key: ${JASYPT_ENCRYPTOR_KEY}

aws:
  ses:
    from: ${AWS_SES_FROM}

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false #CloudFormation 스택 수동 관리 설정
    s3:
      bucket: ${AWS_S3_BUCKET}
    cloud-front:
      deploy-domain: ${CLOUD_FRONT_DEPLOY_DOMAIN}

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        highlight_sql: true
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
  data:
    web:
      pageable:
        one-indexed-parameters: false

logging:
  level:
    root: info
    org.hibernate.sql: info
    org.hibernate.type.descriptor.sql: trace
    com.project.foradhd: debug

google:
  places:
    api-key: ${GOOGLE_PLACES_API_KEY}
    url: ${GOOGLE_PLACES_URL}

---
spring:
  config:
    activate:
      on-profile: dev
    import: aws-parameterstore:/db-config/dev/
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        highlight_sql: true
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
  data:
    web:
      pageable:
        one-indexed-parameters: false

logging:
  level:
    root: info
    org.hibernate.sql: info
    org.hibernate.type.descriptor.sql: trace
    com.project.foradhd: debug

---
spring:
  config:
    activate:
      on-profile: prod
    import: aws-parameterstore:/db-config/prd/
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        highlight_sql: true
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
  data:
    web:
      pageable:
        one-indexed-parameters: false

logging:
  level:
    root: info
    org.hibernate.sql: info
    org.hibernate.type.descriptor.sql: info
    com.project.foradhd: info
