spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(yPa6ipA0+nlvFpE72iedbvxW8NvynFE/bEfbJFLTMZWxrhsBwQhwH0WDLDFPpzy2)
            client-secret: ENC(HSBO2/bj2ClUaqv/HXwlmA2lnw9+9+Ju3CezbH5Hq4HGnsKXZa+K5o3THKxjTemX)
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - account_email
            #비즈앱 등록 후 접근 가능
#              - name
#              - birthday
#              - birthyear
#              - age_range
#              - gender
          naver:
            client-id: ENC(FGYIfJlxdtT4NyOxnV80uuttXOM8NI1FUcsBqSyUmtk=)
            client-secret: ENC(9y68M+H96/5a0h6oX1zgAKCC27yBO5ll)
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - email
              - name
              - birthday
              - birthyear
              - age
              - gender
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response