spring:
  profiles:
    default: dev
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_ID}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        highlight_sql: true
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
  data:
    web:
      pageable:
        one-indexed-parameters: true

logging:
  level:
    root: info
    org.hibernate.sql: info
    org.hibernate.type.descriptor.sql: trace
    com.project.foradhd: debug

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        highlight_sql: true
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
  data:
    web:
      pageable:
        one-indexed-parameters: true

logging:
  level:
    root: info
    org.hibernate.sql: info
    org.hibernate.type.descriptor.sql: info
    com.project.foradhd: info
